# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3.9139
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: roxygenize
        # roxygen requires loading pkg -> add dependencies from DESCRIPTION
        additional_dependencies:
        -    bench@1.1.1
        -    callr@3.7.0
        -    cli@3.0.1
        -    dplyr@1.0.7
        -    fs@1.5.0
        -    gert@1.3.2
        -    ggplot2@3.3.5
        -    glue@1.4.2
        -    knitr@1.33
        -    magrittr@2.0.1
        -    mockery@0.4.2
        -    openssl@1.4.5
        -    purrr@0.3.4
        -    remotes@2.4.0
        -    rlang@0.4.11
        -    rmarkdown@2.10
        -    testthat@3.0.4
        -    tibble@3.1.4
        -    usethis@2.0.1
        -    vctrs@0.3.8
        -    withr@2.4.2
        -    r-lib/pkgapi
        require_serial: True # https://github.com/pre-commit-ci/runner-image/issues/93#issuecomment-927257158
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          data/.*|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.pdf|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*\.odt|
          .*\.png|
          \.github/workflows/.*\.yaml|
          API|
          inst/touchstone\.yaml|
          inst/config\.json|
          LICENCE\.md|
          tests/testthat/_snaps/.*|
          API
          )$
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
        exclude:  >
          (?x)^(
          inst/script\.R|
          README\.Rmd|
          tests/testthat/test-prepare\.R|
          inst/script\.R|
          vignettes/touchstone\.Rmd
          )$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: >
          (?x)^(
          tests/testthat/_snaps/.*|
          .*\.Rd
          )$
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
